src/includes/frontend/up-table-functions.php

[UpStream-issue#4.zip](https://github.com/upstreamplugin/UpStream/files/925751/UpStream-issue.4.zip)

Fix issue #4

---

src/includes/admin/assets/css/upstream.css
src/includes/admin/class-up-admin-bugs-page.php
src/includes/admin/class-up-admin-tasks-page.php

[UpStream-issue#8.zip](https://github.com/upstreamplugin/UpStream/files/926009/UpStream-issue.8.zip)

Fix issue #8

---

src/templates/global/header.php

[UpStream-issue#7.zip](https://github.com/upstreamplugin/UpStream/files/929864/UpStream-issue.7.zip)

Fix issue #7

---

src/includes/up-labels.php

[UpStream-issue#9.zip](https://github.com/upstreamplugin/UpStream/files/930243/UpStream-issue.9.zip)

Fix issue #9

---

src/includes/admin/assets/css/upstream.css

Fix toolbar buttons in Text mode on Project Description editor.

Fix issue #20

---

src/includes/admin/metaboxes/class-up-metaboxes-projects.php

Replace textarea field for a WYSIWYG editor instance.

Fix issue #21

---

src/includes/admin/assets/css/upstream.css
src/includes/admin/metaboxes/class-up-metaboxes-projects.php
src/readme.txt
src/upstream.php

- Fixed UI bug in Project Description editor where all buttons position were messed up in Text Mode
- Replaced Tasks Note textarea with a WYSIWYG editor

v1.6.1 - Maintenance Release

---

src/includes/class-up-roles.php

Removed author metabox

---

src/includes/admin/assets/css/upstream.css

Removes max-width from metaboxes

---

src/includes/admin/assets/js/edit-project.js

Fix issue #18

---

src/includes/up-general-functions.php

Fix issue #28

---

src/includes/admin/class-up-admin-bugs-page.php
src/includes/admin/class-up-admin-project-columns.php
src/includes/admin/class-up-admin-tasks-page.php
src/includes/admin/metaboxes/class-up-metaboxes-projects.php
src/includes/frontend/up-table-functions.php
src/includes/up-general-functions.php
src/templates/global/sidebar.php
src/templates/single-project.php
src/templates/single-project/bugs.php
src/templates/single-project/details.php
src/templates/single-project/files.php
src/templates/single-project/milestones.php
src/templates/single-project/my-bugs.php
src/templates/single-project/my-tasks.php
src/templates/single-project/overview.php
src/templates/single-project/tasks.php

Fix issue #6

---

src/includes/admin/class-up-admin-options.php
src/includes/admin/class-up-admin-project-columns.php
src/includes/admin/class-up-admin-projects-menu.php
src/includes/admin/class-up-admin-tasks-page.php
src/includes/admin/metaboxes/class-up-metaboxes-projects.php
src/includes/admin/options/class-up-options-general.php
src/includes/frontend/up-table-functions.php
src/includes/up-general-functions.php
src/templates/global/sidebar.php
src/templates/single-project.php
src/templates/single-project/discussion.php
src/templates/single-project/files.php
src/templates/single-project/milestones.php
src/templates/single-project/my-tasks.php
src/templates/single-project/overview.php
src/templates/single-project/tasks.php

- Added new options to toggle Tasks, Milestones, Files and Discussion sections globally - #37

Fix issue #37

---

src/templates/global/sidebar.php
src/templates/global/top-nav.php
src/templates/single-project.php

Fixed hardcoded URLs on frontend

---

src/includes/admin/options/class-up-options-general.php

Display client logo and project name on frontend login page as default

---

src/includes/admin/metaboxes/metabox-functions.php
src/includes/up-client-functions.php
src/readme.txt
src/upstream.php

Changed:
* Moved metaboxes filters to the bottom
* Client logo and Project name are now displayed by default on frontend login page (this can be changed on the options page) - Fix #88 
Fixed:
* Internal code cleanup

Release 1.10.2

---

src/includes/admin/assets/css/upstream.css
src/includes/admin/metaboxes/class-up-metaboxes-projects.php

Fix issue #83

---

src/upstream.php

Since dev contains minor changes, its ok to update the v1.1.0.3 release branch.

Updating the release branch with the latest changes on dev

---

src/includes/admin/assets/css/upstream.css
src/includes/admin/assets/js/edit-client.js
src/includes/admin/class-up-admin-client-columns.php
src/includes/admin/class-up-admin-project-columns.php
src/includes/admin/class-up-admin-projects-menu.php
src/includes/admin/class-up-admin.php
src/includes/admin/metaboxes/class-up-metaboxes-clients.php
src/includes/admin/metaboxes/class-up-metaboxes-projects.php
src/includes/admin/metaboxes/metabox-functions.php
src/includes/admin/up-enqueues.php
src/includes/frontend/class-up-login.php
src/includes/frontend/class-up-template-loader.php
src/includes/frontend/up-table-functions.php
src/includes/frontend/up-template-functions.php
src/includes/up-general-functions.php
src/includes/up-permissions-functions.php
src/readme.txt
src/templates/archive-project.php
src/templates/assets/js/upstream.js
src/templates/global/sidebar.php
src/templates/global/top-nav.php
src/templates/login.php
src/templates/single-project.php
src/upstream.php

* `UpStream Users` and `UpStream Administrators` are now capable of logging in via `/projects` page
* `UpStream Client Users` **cannot** log in via `/projects` page
* `UpStream Users` no longer can log in projects using the client's password
* Metaboxes filters were moved from the top to the bottom of the box
* Appearance enhancements
* Fixed random logo appearing in `/projects` page
* Fixed bug giving some users a hard time logging in a project
* Fixed uncommon redirection bug after logging off on frontend
* Fixed bug causing some usernames to be blank in several places - issue #90 
* `UpStream Users` no longer can access projects in which they're not involved in
* Fixed some clients losing their password after saving the form

v1.10.3 - Patch Release

---

src/templates/archive-project.php
src/templates/assets/js/upstream.js
src/templates/single-project/details.php

Fix issue #66

---

src/includes/frontend/up-table-functions.php
src/readme.txt
src/templates/archive-project.php
src/templates/assets/js/upstream.js
src/templates/single-project/details.php
src/upstream.php

Changed:
* Fix #66 - Clearer Project timeframe date-strings
Fixed:
* Fixed bug that was causing items to lose their dates if edited on localized sites
* Empty columns on frontend tables now receive "none"
* Some code redundancies
* Some columns on frontend tables are no longer orderable

v1.10.4 - Patch Release

---

src/includes/admin/assets/js/edit-project.js
src/includes/admin/class-up-admin-projects-menu.php
src/includes/admin/metaboxes/class-up-metaboxes-projects.php
src/includes/class-up-counts.php
src/includes/up-install.php
src/readme.txt
src/templates/single-project/files.php
src/upstream.php

**Changed:**
- Don't autofill Start and End Date - issue #130
**Fixed:**
- Bugs and Task notifications show even if disabled - issue #129
- Task 1, Task 2, Task 3 keep appearing - issue #127
- Tasks notes aren't full width - issue #125
- Missing avatars - issue #123

v1.11.3 - Patch Release

---

src/includes/admin/assets/js/edit-project.js

Prevent initially disabled/blocked items from being removed by users

---

src/includes/admin/metaboxes/class-up-metaboxes-projects.php

Fix tasks start and end dates always having a value

---

src/includes/admin/assets/js/edit-project.js
src/includes/admin/metaboxes/class-up-metaboxes-projects.php
src/readme.txt
src/upstream.php

**Fixed:**
* Fixed UpStream Users being able to delete tasks that were not assigned to them
* Fixed remaining bug on Tasks dates always coming back with a value after saving them blank

v1.11.4 - Patch Release

---

src/includes/frontend/up-table-functions.php
src/readme.txt
src/upstream.php

**Added:**
- Added `Requires PHP` rule to [readme.txt](https://github.com/upstreamplugin/UpStream/blob/master/src/readme.txt)
- Added support for due date reminders through [Email Notifications](https://upstreamplugin.com/extensions/email-notifications/) extension

v1.11.5 - Patch Release

---

src/includes/admin/metaboxes/metabox-functions.php
src/includes/frontend/up-template-functions.php
src/includes/up-project-functions.php
src/languages/upstream.pot
src/readme.txt
src/templates/assets/css/upstream.css
src/templates/single-project/overview.php
src/upstream.php

**Changed:**
* Changed overview boxes items order
**Fixed:**
* Attempt to fix some PHP errors

v1.12.1 - Patch Release

---

src/includes/admin/assets/js/edit-project.js
src/includes/admin/metaboxes/class-up-metaboxes-projects.php
src/readme.txt

- Fixed project's permalink not appearing on form in admin

Fix issue #176

---

src/readme.txt
src/templates/single-project/overview.php

Fix issue #197

---

src/readme.txt
src/templates/single-project/bugs.php

Fix issue #209

---

src/includes/class-up-project.php
src/readme.txt

Fix issues #195 and #210

---

src/includes/class-up-roles.php
src/includes/up-permissions-functions.php
src/readme.txt
src/upstream.php

Fix issue #220

---

src/includes/class-up-project-activity.php
src/readme.txt

Fix issue #221

---

src/readme.txt
src/templates/assets/css/upstream.css

Fix issue #219

---

src/includes/admin/metaboxes/metabox-functions.php
src/includes/frontend/up-table-functions.php
src/readme.txt

Empty Details for Milestones, Tasks, Bug, Files

---

src/includes/admin/up-enqueues.php
src/readme.txt
src/upstream.php

Fixed some assets being loaded on every page in admin

---

src/includes/admin/options/class-up-options-bugs.php
src/includes/admin/options/class-up-options-extensions.php
src/includes/admin/options/class-up-options-general.php
src/includes/admin/options/class-up-options-milestones.php
src/includes/admin/options/class-up-options-projects.php
src/includes/admin/options/class-up-options-tasks.php
src/readme.txt

Remove the "Settings" label from the admin area

---

src/includes/admin/up-enqueues.php
src/readme.txt
src/upstream.php

* Fixed white screen on settings page
* Fixed CMB2 loading bug

v1.13.3 - Patch Release

---

src/includes/admin/metaboxes/metabox-functions.php
src/includes/frontend/up-enqueues.php
src/readme.txt
src/templates/assets/css/upstream.css
src/templates/assets/js/upstream.js
src/upstream.php

Removed stray "none" text and fix text consistency on frontend

---

src/includes/admin/metaboxes/class-up-metaboxes-clients.php
src/readme.txt
src/upstream.php

Remove notice about recent changes on Clients

---

src/includes/admin/metaboxes/class-up-metaboxes-projects.php
src/readme.txt
src/upstream.php

Fix potential PHP erros and warnings

---

src/includes/admin/assets/js/edit-project.js
src/readme.txt
src/upstream.php

Fixed some Comments tabs not working on admin

---

src/includes/admin/class-up-admin-client-columns.php
src/includes/admin/class-up-admin-projects-menu.php
src/includes/admin/metaboxes/class-up-metaboxes-projects.php
src/includes/admin/options/class-up-options-general.php
src/includes/class-up-comments.php
src/includes/class-up-project-activity.php
src/includes/frontend/up-template-functions.php
src/includes/up-post-types.php
src/languages/upstream.pot
src/readme.txt
src/templates/assets/css/upstream.css
src/templates/assets/js/upstream.js
src/templates/global/sidebar.php
src/templates/single-project.php
src/templates/single-project/discussion.php
src/upstream.php

* Tags can now be assigned to Projects
* Added "Disable Project Overview" option - #308 
* Added "Disable Project Details" option - #224 
* Auto scroll to particular comments via URL 
* "Comments on <section>" options labels were renamed to "Disable Discussion on <section>" - #308 
* Some options were grouped for better UX - #308 
* Fixed a couple of strings not being translated as they should - #328

v1.14.0 - Minor Release

---

.editorconfig
.gitignore
package.json
scripts/build.js
scripts/build.sh
src/includes/admin/metaboxes/class-up-metaboxes-clients.php
src/includes/admin/metaboxes/metabox-functions.php
src/includes/up-client-functions.php
src/includes/up-general-functions.php
src/includes/up-project-functions.php
src/readme.txt
src/upstream.php

* Fixed CMB2 not being loaded correctly in a multisite environment - #345 
* Fixed some DB calls triggering errors in multisite environments

v1.4.1 - Patch Release

---

src/includes/frontend/class-up-template-loader.php
src/includes/up-general-functions.php
src/readme.txt
src/templates/login.php

Fixed 404 redirects after login/logout in some environments

---

src/readme.txt
src/templates/single-project/bugs.php
src/templates/single-project/files.php
src/templates/single-project/tasks.php

"Title" search fields placeholders are not individually i18n scoped anymore

---

src/includes/admin/class-up-admin.php
src/includes/admin/metaboxes/class-up-metaboxes-projects.php
src/includes/class-up-project.php
src/readme.txt

Normalize timezones inconsistencies

---

src/includes/admin/class-up-admin.php
src/includes/admin/metaboxes/class-up-metaboxes-projects.php
src/includes/class-up-project.php
src/includes/frontend/class-up-template-loader.php
src/includes/up-general-functions.php
src/languages/upstream.pot
src/readme.txt
src/templates/assets/js/upstream.js
src/templates/login.php
src/templates/single-project/bugs.php
src/templates/single-project/files.php
src/templates/single-project/tasks.php
src/upstream.php

* "Title" search fields placeholders are not individually i18n scoped anymore - #363 
* Fixed 404 redirects after login/logout in some environments - #366 
* Fixed Start/End/Due Date fields not always being stored as GMT/UTC - #365

v1.15.1 - Patch Release

---

src/includes/admin/assets/css/upstream.css
src/includes/admin/assets/js/edit-project.js
src/includes/admin/class-up-admin-bugs-page.php
src/includes/admin/class-up-admin-tasks-page.php
src/includes/admin/metaboxes/class-up-metaboxes-projects.php
src/includes/admin/metaboxes/metabox-functions.php
src/includes/admin/up-enqueues.php
src/includes/class-up-counts.php
src/includes/class-up-project-activity.php
src/includes/class-up-project.php
src/includes/frontend/class-up-view.php
src/includes/frontend/up-table-functions.php
src/readme.txt
src/templates/assets/js/upstream.js
src/templates/single-project/bugs.php
src/templates/single-project/tasks.php
src/upstream.php

Add support for multiple assignees

---

src/includes/admin/class-up-admin-bugs-page.php
src/includes/admin/class-up-admin-pointers.php
src/includes/admin/class-up-admin-project-columns.php
src/includes/admin/class-up-admin-tasks-page.php
src/includes/admin/class-up-admin.php
src/includes/admin/metaboxes/class-up-metaboxes-clients.php
src/includes/admin/metaboxes/class-up-metaboxes-projects.php
src/includes/class-up-comments.php
src/includes/class-up-counts.php
src/includes/frontend/class-up-view.php
src/includes/up-general-functions.php
src/includes/up-permissions-functions.php
src/languages/upstream.pot
src/readme.txt
src/templates/single-project/details.php

Fixed recent PHP warnings thrown under PHP 7.2

---

src/includes/admin/class-up-admin.php
src/includes/admin/metaboxes/class-up-metaboxes-projects.php
src/includes/class-up-comment.php
src/includes/class-up-comments.php
src/includes/up-general-functions.php
src/languages/upstream.pot
src/readme.txt
src/upstream.php

* Added option under user's profile to choose whether to be notified when someone replies to his comments
* Users are now notified about comment replies
* Fixed yet another error with malconversion of some time zones

v1.16.2 - Patch Release

---

src/includes/admin/assets/js/edit-project.js
src/includes/admin/metaboxes/class-up-metaboxes-projects.php
src/includes/frontend/up-enqueues.php
src/includes/up-permissions-functions.php
src/languages/upstream.pot
src/readme.txt
src/templates/archive-project.php
src/templates/global/footer.php
src/templates/global/sidebar.php
src/templates/single-project.php
src/upstream.php

* Increased maximum execution time for frontend scripts
* Minor performance enhancements on front end pages
* Fixed uncommon bug where jQuery UI DatePicker plugin was being loaded on frontend
* Fixed filters on admin project page that can have multiple values - #433 
* Fixed PHP warnings - #430

v1.16.4 - Patch Release

---

includes/class-up-counter.php

PHP error in Issues area
Warning: array_merge(): Argument #2 is not an array

#773 issue fixed

---

includes/class-up-counter.php
includes/class-up-counts.php
includes/class-up-project.php
templates/assets/js/upstream.js

Fixed Issues

---

includes/admin/metaboxes/metabox-functions.php

Fixed issue: #755 (Activity numbers not accurate in frontend or admin)

---

includes/frontend/up-table-functions.php
templates/archive-project.php
templates/assets/js/upstream.js

Fixed Issue : #797 (Show how many search results are returned)

---

templates/single-project/overview.php

Changed file : 
- templates / single-project / overview.php

Fixed Issue : #755 (fixed small issue)

---

includes/admin/assets/js/admin.js
includes/admin/class-up-admin-client-columns.php
includes/admin/metaboxes/class-up-metaboxes-clients.php
includes/admin/up-enqueues.php

Updated files :
- includes/admin/assets/js/admin.js
- includes/admin/metaboxes/class-up-metaboxes-clients.php
- includes/admin/up-enqueues.php
- includes/admin/class-up-admin-client-columns.php

Sergei/issue#77 UpStream

---

includes/frontend/up-template-functions.php
includes/up-general-functions.php

Changed file:
- upstream / includes / up-general-functions.php

Updated Upstream Issue #785 (show username on front-end)

---

includes/admin/assets/js/admin.js
includes/up-general-functions.php
templates/archive-project.php

Changed file:
- UpStream / includes / up-general-functions.php (updated date format)

Fixed UpStream Issue : #854 (Date sorting is incorrect)

---

includes/class-up-comments.php

As per tasks and milestones, email comments/discussions to all project members.
More consistent with how emails work for other modules
Will need to provide an option to turn this off. This should be provided in the new notification update screen options slated for a future release.

Email comments/discussions to all project members.

---

includes/admin/class-up-admin.php

Reverts upstreamplugin/UpStream#869

Revert "Fixed UpStream Issue : #827 (Block Client Users from accessing the pr…"
